CREATE DATABASE IF NOT EXISTS realtime_maps CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE realtime_maps;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(200) UNIQUE,
  phone VARCHAR(32) UNIQUE,
  hashed_password VARCHAR(256),
  display_name VARCHAR(200),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS search_history (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT,
  query VARCHAR(512),
  lat DOUBLE,
  lng DOUBLE,
  ts DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS route_reports (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT,
  type VARCHAR(64),
  description TEXT,
  lat DOUBLE,
  lng DOUBLE,
  ts DATETIME DEFAULT CURRENT_TIMESTAMP,
  trust_score INT DEFAULT 0,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;
